name: build-master

on:
   push:
      paths-ignore:
         - 'doc/**'
         - '*.md'
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            product: ["IC-2019.3", "IC-2020.1", "IC-2020.2", "AS-3.6", "AS-4.0", "AS-4.1"]
         max-parallel: 3

      steps:
         -  name: Checkout the repo
            uses: actions/checkout@v2
            with:
               fetch-depth: 0

         -  name: Run ubuntu tests
            run: ./gradlew check
            env:
               PRODUCT_NAME: ${{ matrix.product }}

         -  name: Bundle the build report
            if: failure()
            run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

         -  name: Upload the build report
            if: failure()
            uses: actions/upload-artifact@master
            with:
               name: error-report
               path: build-reports.zip

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
